version: '3'
services:
  backend:
    environment:
      - STORE_TYPE=inmemory
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ozontesttask
      - PG_SSLMODE=disable
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d

networks:
  mynetwork: